name: ta
description: YRDSB Teach Assist
version: 1.5.2+21

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: ^6.0.1
  shared_preferences: ^0.5.4+5
  after_layout: ^1.0.7+2
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  http: ^0.12.0+2
  sprintf: ^4.0.2
  syncfusion_flutter_charts: ^17.3.26
  flutter_selectable_text: ^0.3.1
  firebase_analytics: ^5.0.6
  intl: ^0.15.8
  firebase_performance: ^0.3.1+4
  firebase_crashlytics: ^0.1.1+2
  package_info: ^0.4.0+10
  flutter_custom_tabs: ^0.6.0
  flutter_statusbarcolor: ^0.2.3
  sticky_headers: ^0.1.8+1
  quiver: ^2.0.5
  transparent_image: ^1.0.0
  keyboard_visibility: ^0.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3
  flutter_native_splash: ^0.1.8+2

flutter_icons:
  android: false
  ios: true
  image_path: "assets/icon/ios_launcher_icon.png"

flutter_native_splash:
  image: assets/icon/splash_icon.png
  color: "03a9f4"


flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/icon.ttf