name: ta
description: YRDSB Teach Assist
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: ^5.1.6
  shared_preferences: ^0.5.3+4
  after_layout: ^1.0.7
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  http: ^0.12.0+2
  percent_indicator: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3

flutter_icons:
  android: false
  ios: true
  image_path: "assets/icon/ios_launcher_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/