name: ta
description: YRDSB Teach Assist
version: 1.7.29+74

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_messaging: ^6.0.13
  shared_preferences: ^0.5.6+3
  after_layout: ^1.0.7+2
  flutter_cupertino_localizations: ^1.0.1
  http: ^0.12.0+2
  sprintf: ^4.0.2
  syncfusion_flutter_charts: ^18.2.45
  flutter_selectable_text: ^0.3.1
  firebase_analytics: ^5.0.11
  intl: ^0.16.0
  firebase_performance: ^0.3.1+8
  package_info: ^0.4.0+16
  flutter_custom_tabs: ^0.6.0
  flutter_statusbarcolor: ^0.2.3
  sticky_headers: ^0.1.8+1
  quiver: ^2.0.5
  flutter_privacy_screen: ^1.1.0
  flutter_keyboard_visibility: ^0.7.0
  share_extend: ^1.1.3
  path_provider: ^1.5.1
  flutter_spinkit: ^4.1.2+1
  flutter_markdown: ^0.3.4
  pull_to_refresh: ^1.5.8
  transparent_image: ^1.0.0
  fragment: ^0.3.1
  firebase_crashlytics: ^0.1.3+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4
  flutter_native_splash: ^0.1.9

flutter_icons:
  android: false
  ios: true
  image_path: "assets/icons/ios_launcher_icon.png"

flutter_native_splash:
  image: assets/icons/splash_icon.png
  color: "03a9f4"


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/icon.ttf
    - family: CustomIcons2
      fonts:
        - asset: assets/fonts/icon2.ttf
