name: ta
description: YRDSB Teach Assist
version: 1.7.33+78

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_messaging: ^7.0.3
  shared_preferences: ^0.5.12+4
  after_layout: ^1.0.7+2
  flutter_cupertino_localizations: ^1.0.1
  http: ^0.12.2
  sprintf: ^5.0.0
  syncfusion_flutter_charts: ^18.4.32+1
  flutter_selectable_text: ^0.3.1
  firebase_analytics: ^6.3.0
  intl: ^0.16.1
  firebase_performance: ^0.4.3
  package_info: ^0.4.3+2
  flutter_custom_tabs: ^0.6.0
  flutter_statusbarcolor: ^0.2.3
  sticky_headers: ^0.1.8+1
  quiver: ^2.1.5
  flutter_privacy_screen: ^1.1.0
  flutter_keyboard_visibility: ^4.0.2
  share_extend: ^1.1.9
  path_provider: ^1.6.24
  flutter_spinkit: ^4.1.2+1
  flutter_markdown: ^0.5.1
  pull_to_refresh: ^1.6.3
  transparent_image: ^1.0.0
  fragment: ^0.3.1
  firebase_crashlytics: ^0.2.4
  convert: ^2.1.1
  clipboard: ^0.1.2+8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  flutter_native_splash: ^0.1.9

flutter_icons:
  android: false
  ios: true
  image_path: "assets/icons/ios_launcher_icon.png"

flutter_native_splash:
  image: assets/icons/splash_icon.png
  color: "03a9f4"


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/icon.ttf
    - family: CustomIcons2
      fonts:
        - asset: assets/fonts/icon2.ttf
