name: ta
description: YRDSB Teach Assist
version: 1.2.6+10

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: ^5.1.6
  shared_preferences: ^0.5.3+4
  after_layout: ^1.0.7
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  http: ^0.12.0+2
  sprintf: ^4.0.2
  syncfusion_flutter_charts: ^1.0.0-beta.4
  flutter_selectable_text: ^0.3.1
  firebase_analytics: ^5.0.2
  intl: 0.15.8
  firebase_performance: ^0.3.0+5
  firebase_crashlytics: ^0.1.0+3
  package_info: ^0.4.0+9
  url_launcher: ^5.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3
  flutter_native_splash: ^0.1.8+2

flutter_icons:
  android: false
  ios: true
  image_path: "assets/icon/ios_launcher_icon.png"

flutter_native_splash:
  image: assets/icon/splash_icon.png
  color: "03a9f4"


flutter:
  uses-material-design: true
  assets:
    - assets/images/